listen: ':8081'
mysql: 
  dsn: 'root:xxxxx@2019@tcp(127.0.0.1:3306)/hrtv?charset=utf8&parseTime=true'
  max_conn: 100
  max_idle_conn: 10
redis:
  addr: 127.0.0.1:6379
  password: 
  db: 0
  max_conn: 100
  max_idle_conn: 10
gin:
  mode: debug
  log: console
